title: Cedric Tuttle Portfolio
description: Economics & Data Science Portfolio
# Only show these pages in the top navigation
header_pages:
  - index.md
  - about.md
  - projects.md

sass:
  style: compressed
